# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

# nucleos_antispam:
#   time:
#     min: 1
#     global: true
#   honeypot:
#     global: false
